common: &common
  adapter: postgresql
  host: localhost

development:
  <<: *common
  database: goaltracker

test: &test
  <<: *common
  database: goaltracker_test

production:
  <<: *common

cucumber:
  <<: *test
